services:
  - type: web
    name: room-transfer-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    # UPDATED: using gevent worker
    startCommand: gunicorn --worker-class gevent -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
